### ISSUE TITLE
Providing zoom in photo gallery

### ISSUE THREAD

**Issue by widespaceDLS** [GrowSocial/teaser#7]
FEATURE: Photo Gallery
FEATURE ASPECT: Zoom
ASPECT OBJECTIVE: Provide zoom (enlargement) of selected image in gallery.

ISSUE(S): Method works in Chrome, Safari. Does not work in Firefox, IE
[
Windows 8.1, 10
Firefox 40.0.3
Chrome 44.0.2403.157 m
Safari 5.1.7
IE 11.0.22
]

Bootstrap template “Ecosave” (Light) utilized for teaser.INDEX.HTML  
http://binarytheme.com/demos?theme=ecosave-bootstrap-environment-template

Template design includes “Gallery” feature that provides an opaque overlay (mask) when mouse hover on any photo in gallery is TRUE. 
Opaque overlay mask includes hotspot area that triggers loading an fullsize copy of image to a lightbox, superimposed to display.

In Firefox, IE, overlay mask does not size correctly and hotspot is not visable. No zoom is possible.

Behavior is same in un-modified template at Bootstrap. Problem using Firefox, IE.

**Comment by mishavee** [comment]
Also does not work on mobile phone Chrome 44.0.2403.133, zoomed image is a lot smaller than the image on the page. Phone: Samsung Ace 3.

**Comment by mishavee** [comment]
We can either fix the zoom issue, or replace it with another zoom mechanism, or turn it off and allow each device to zoom in its own way.

**Comment by mishavee** [comment]
I took out the zoom.
